import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Canvas from '@/components/Canvas/Canvas';
import Sidebar from '@/components/Sidebar/Sidebar';
import Label from '@/components/Label/Label';
import Button from '@/components/Button/Button';
import Input from '@/components/Input/Input';
import { useState } from 'react';
import Modal from '@/components/Modal/Modal';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [inputVal, setInputValue] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [coordinates, setCoordinates] = useState({ x: 0, y: 0 });

  const handleChange = () => {
    console.log(inputVal);
  }

  const handleDrop = (x: number, y: number) => {
    setCoordinates({ x, y });
    setShowModal(true);
  };

  const closeModal = () => setShowModal(false);

  const sidebarItems = [
    { id: 'label', displayName: 'Label', component: <Label text='This is a label' /> },
    { id: 'input', displayName: 'Input', component: <Button text='Button' /> },
    { id: 'button', displayName: 'Button', component : <Input value={inputVal} onChange={handleChange} /> },
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Canvas onDrop={handleDrop} />
        <Sidebar items={sidebarItems} />
        {showModal && (
        <Modal isOpen={showModal} onClose={closeModal}>
          <form>
            <label>
              X Coordinate:
              <input type="number" value={coordinates.x} readOnly />
            </label>
            <label>
              Y Coordinate:
              <input type="number" value={coordinates.y} readOnly />
            </label>
            <button type="submit">Save</button>
          </form>
        </Modal>
      )}
      </main>
    </>
  )
}
